general.import = ["themes/rose-pine.toml"]

[terminal]
shell = "nu"

[font]
normal = {family = "JetBrainsMono Nerd Font", style = "Medium"}
bold = {family = "JetBrainsMono Nerd Font", style = "Bold"}
italic = {family = "JetBrainsMono Nerd Font", style = "Italic"}
bold_italic = {family = "JetBrainsMono Nerd Font", style = "Bold Italic"}

[selection]
save_to_clipboard=true

[cursor]
style = {shape="Block",blinking="Always"}

[keyboard]
bindings =[
{key = "Space", mods = "Control", action = "ToggleViMode"},
{key = "N", mods = "Control|Shift", action = "CreateNewWindow"}
]
